using Janus.ORM;
using Janus.ORM.SubSonic.SQLGeneration.Schema;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Janus.Databases.Accounts
{
    public class AccountRecordRelator
    {
        public const string FetchQueryByLogin = "SELECT * FROM accounts WHERE Username = '{0}'";
    }
    [TableName("accounts")]
    public class AccountRecord : IAutoGeneratedRecord
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public byte Role { get; set; }
        public DateTime? BanTime { get; set; }
    }
}
