using Janus.ORM;
using Janus.ORM.SubSonic.SQLGeneration.Schema;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Janus.Databases.Characters
{
    public class CharacterRecordRelator
    {
        public const string FetchQueryByAccountId = "SELECT * FROM characters WHERE AccountId = {0}";
    }
    [TableName("characters")]
    public class CharacterRecord : IAutoGeneratedRecord
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string Name { get; set; }
        public string Rank { get; set; }
        public string ClanName { get; set; }
        public string Bio { get; set; }
        public string Zone { get; set; }
        public int Country { get; set; }
        public int Age { get; set; }
        public int FirstLogin { get; set; }
        public int Type { get; set; }
        public int Sex { get; set; }
        public int Level { get; set; }
        public int Exp { get; set; }
        public int Licence { get; set; }
        public int Cash { get; set; }
        public int Gamecash { get; set; }
        public int Coin { get; set; }
        public int Questpoint { get; set; }
    }
}
